#if UNITY_EDITOR
using System.IO;
using System.Globalization;
using UnityEngine;
using UnityEditor;

namespace R8EOX.Editor.Builders
{
    /// <summary>
    /// Exports buggy spec data to JSON for the interactive viewer playground.
    /// Builds temp prefabs and inspects their actual components — no hardcoded duplication.
    /// Run via R8EOX/Export Viewer Data or automatically when building all buggies.
    /// </summary>
    internal static class BuggySpecExporter
    {
        const string k_HtmlPath = "rc-buggy-viewer.html";
        const string k_StartMarker = "<!-- SPEC_DATA_START";
        const string k_EndMarker = "<!-- SPEC_DATA_END -->";

        [MenuItem("R8EOX/Export Viewer Data")]
        internal static void Export()
        {
            var allSpecs = BuggySpecCatalog.GetAll();
            if (allSpecs.Length == 0) { Debug.LogWarning("[BuggySpecExporter] No specs in catalog"); return; }

            string json = "{\n" +
                BuildSharedFromComponents() + ",\n" +
                BuildMotorPresets() + ",\n";

            // Build first variant's temp prefab to extract colliders/skidplates
            // (shared collision layout — same for all variants)
            var tempGO = RCBuggyBuilder.BuildFromSpec(allSpecs[0]);
            json += BuildCollidersFromPrefab(tempGO) + ",\n" +
                BuildSkidPlatesFromPrefab(tempGO) + ",\n";
            Object.DestroyImmediate(tempGO);

            // Build each variant — key derived from spec name
            json += "  \"variants\": {\n";
            for (int i = 0; i < allSpecs.Length; i++)
            {
                var spec = allSpecs[i];
                string key = spec.Name.Replace("Buggy", "").Trim().ToLowerInvariant();
                if (string.IsNullOrEmpty(key)) key = $"variant{i}";
                var go = RCBuggyBuilder.BuildFromSpec(spec);
                json += BuggySpecSerializer.BuildVariantFromPrefab(key, spec, go);
                Object.DestroyImmediate(go);
                if (i < allSpecs.Length - 1) json += ",";
                json += "\n";
            }
            json += "  }\n}";

            InjectIntoHtml(json);
        }

        static void InjectIntoHtml(string json)
        {
            string htmlPath = Path.Combine(Application.dataPath, "..", k_HtmlPath);
            if (!File.Exists(htmlPath))
            {
                Debug.LogError($"[BuggySpecExporter] {k_HtmlPath} not found");
                return;
            }

            string html = File.ReadAllText(htmlPath);
            int startIdx = html.IndexOf(k_StartMarker);
            int endIdx = html.IndexOf(k_EndMarker);
            if (startIdx < 0 || endIdx < 0)
            {
                Debug.LogError($"[BuggySpecExporter] SPEC_DATA markers not found in {k_HtmlPath}");
                return;
            }

            string replacement =
                k_StartMarker + " (auto-generated by R8EOX > Export Viewer Data — do not edit manually) -->\n" +
                "<script>window.BUGGY_SPECS = " + json + ";</script>\n" +
                k_EndMarker;

            html = html.Substring(0, startIdx) + replacement + html.Substring(endIdx + k_EndMarker.Length);
            File.WriteAllText(htmlPath, html);
            Debug.Log($"[BuggySpecExporter] Updated {k_HtmlPath} with spec data");
        }

        // ---- Shared Constants (read from actual component defaults) ----

        static string BuildSharedFromComponents()
        {
            // Create temp components to read their serialized defaults
            var tempGO = new GameObject("_ExporterTemp");
            var vm = tempGO.AddComponent<Rigidbody>();
            var vmComp = tempGO.AddComponent<R8EOX.Vehicle.VehicleManager>();
            var dtGO = new GameObject("Drivetrain");
            dtGO.transform.SetParent(tempGO.transform);
            var dt = dtGO.AddComponent<R8EOX.Vehicle.Internal.Drivetrain>();

            var vmSO = new SerializedObject(vmComp);
            var dtSO = new SerializedObject(dt);

            float flipHeight = ReadConst(vmSO, "_tumbleEngageDeg") > 0 ? 0.35f : 0.35f;
            // Read actual serialized defaults
            float steeringSpeed = vmSO.FindProperty("_steeringSpeed")?.floatValue ?? 7f;
            float steeringSpeedLimit = vmSO.FindProperty("_steeringSpeedLimit")?.floatValue ?? 8f;
            float steeringHighSpeedFactor = vmSO.FindProperty("_steeringHighSpeedFactor")?.floatValue ?? 0.4f;
            float throttleRampDown = vmSO.FindProperty("_throttleRampDown")?.floatValue ?? 10f;
            float tumbleEngage = vmSO.FindProperty("_tumbleEngageDeg")?.floatValue ?? 50f;
            float tumbleFull = vmSO.FindProperty("_tumbleFullDeg")?.floatValue ?? 70f;
            float tumbleHysteresis = vmSO.FindProperty("_tumbleHysteresisDeg")?.floatValue ?? 5f;
            float tumbleBounce = vmSO.FindProperty("_tumbleBounce")?.floatValue ?? 0.35f;
            float tumbleFriction = vmSO.FindProperty("_tumbleFriction")?.floatValue ?? 0.3f;

            Object.DestroyImmediate(tempGO);

            float scr = R8EOX.Vehicle.Internal.RaycastWheel.SphereCastRadius;

            return "  \"shared\": {\n" +
                F("    \"sphereCastRadius\": {0}", scr) + ",\n" +
                F("    \"steeringSpeed\": {0}", steeringSpeed) + ",\n" +
                F("    \"steeringSpeedLimit\": {0}", steeringSpeedLimit) + ",\n" +
                F("    \"steeringHighSpeedFactor\": {0}", steeringHighSpeedFactor) + ",\n" +
                F("    \"throttleRampDown\": {0}", throttleRampDown) + ",\n" +
                F("    \"tumbleEngage\": {0}", tumbleEngage) + ",\n" +
                F("    \"tumbleFull\": {0}", tumbleFull) + ",\n" +
                F("    \"tumbleHysteresis\": {0}", tumbleHysteresis) + ",\n" +
                F("    \"tumbleBounce\": {0}", tumbleBounce) + ",\n" +
                F("    \"tumbleFriction\": {0}", tumbleFriction) + "\n" +
                "  }";
        }

        static float ReadConst(SerializedObject so, string name)
        {
            var prop = so.FindProperty(name);
            return prop != null ? prop.floatValue : 0f;
        }

        // ---- Motor Presets (read from registry) ----

        static string BuildMotorPresets()
        {
            string[] names = { "21.5T", "17.5T", "13.5T", "9.5T", "5.5T", "1.5T" };
            var presets = R8EOX.Vehicle.Internal.MotorPresetRegistry.Presets;
            string result = "  \"motorPresets\": [\n";
            for (int i = 0; i < presets.Length && i < names.Length; i++)
            {
                var p = presets[i];
                result += $"    {{ \"name\": \"{names[i]}\", " +
                    F("\"engineForce\": {0}", p.EngineForceMax) + ", " +
                    F("\"brakeForce\": {0}", p.BrakeForce) + ", " +
                    F("\"reverseForce\": {0}", p.ReverseForce) + ", " +
                    F("\"coastDrag\": {0}", p.CoastDrag) + ", " +
                    F("\"maxSpeed\": {0}", p.MaxSpeed) + ", " +
                    F("\"throttleRampUp\": {0}", p.ThrottleRampUp) + " }";
                if (i < presets.Length - 1) result += ",";
                result += "\n";
            }
            result += "  ]";
            return result;
        }

        // ---- Colliders (inspected from built prefab) ----

        static string BuildCollidersFromPrefab(GameObject root)
        {
            string result = "  \"colliders\": [\n";
            var colliders = root.GetComponents<BoxCollider>();
            for (int i = 0; i < colliders.Length; i++)
            {
                var c = colliders[i];
                var s = c.size; var ct = c.center;
                result += $"    {{ \"name\": \"{c.gameObject.name}_{i}\", " +
                    $"\"size\": [{F(s.x)}, {F(s.y)}, {F(s.z)}], " +
                    $"\"center\": [{F(ct.x)}, {F(ct.y)}, {F(ct.z)}] }}";
                if (i < colliders.Length - 1) result += ",";
                result += "\n";
            }
            result += "  ]";
            return result;
        }

        // ---- Skid Plates (child objects with BoxCollider + rotation) ----

        static string BuildSkidPlatesFromPrefab(GameObject root)
        {
            string result = "  \"skidPlates\": [\n";
            bool first = true;
            foreach (Transform child in root.transform)
            {
                if (!child.name.StartsWith("SkidPlate")) continue;
                var col = child.GetComponent<BoxCollider>();
                if (col == null) continue;
                if (!first) result += ",\n";
                first = false;
                var s = col.size; var p = child.localPosition;
                float rotZ = child.localEulerAngles.z;
                if (rotZ > 180) rotZ -= 360; // normalize to signed
                result += $"    {{ \"name\": \"{child.name}\", " +
                    $"\"size\": [{F(s.x)}, {F(s.y)}, {F(s.z)}], " +
                    $"\"position\": [{F(p.x)}, {F(p.y)}, {F(p.z)}], " +
                    F("\"rotZ\": {0}", rotZ) + " }";
            }
            result += "\n  ]";
            return result;
        }

        // ---- Formatting helpers (delegate to serializer) ----

        static string F(float v) => BuggySpecSerializer.F(v);
        static string F(string fmt, float v) => BuggySpecSerializer.F(fmt, v);
    }
}
#endif
