#!/usr/bin/env bash
# C# lint rules for R8EOX project
# Sourced by tools/hooks/pre-commit — do not run directly.

is_unity_generated() {
  local file="$1"
  case "$file" in
    Library/*|Packages/*|ProjectSettings/*|Temp/*|UserSettings/*) return 0 ;;
    Assets/Plugins/Roslyn/*) return 0 ;;
    *.Designer.cs|*AssemblyInfo.cs) return 0 ;;
  esac
  if git show ":${file}" 2>/dev/null | head -5 | grep -q '<auto-generated>'; then
    return 0
  fi
  return 1
}

lint_cs_file() {
  local file="$1"
  local errors=0
  local content
  content=$(git show ":${file}" 2>/dev/null) || return 0

  # 300 LINE LIMIT
  local line_count
  line_count=$(echo "$content" | wc -l | tr -d ' ')
  if [ "$line_count" -gt 300 ]; then
    echo "FAIL [line-limit] ${file}: ${line_count} lines (max 300)"
    errors=$((errors + 1))
  fi

  # NAMESPACE CHECK
  if ! echo "$content" | grep -qE '^\s*namespace\s+R8EOX'; then
    echo "FAIL [namespace] ${file}: missing R8EOX namespace"
    errors=$((errors + 1))
  fi

  # LEGACY INPUT BAN (skip comments)
  local legacy_hits
  legacy_hits=$(echo "$content" | grep -nE 'Input\.(GetKey|GetAxis|GetButton|GetMouseButton|anyKey|mousePosition)' | grep -vE '^\s*[0-9]*:\s*//' || true)
  if [ -n "$legacy_hits" ]; then
    echo "FAIL [input-system] ${file}: legacy Input API — use new Input System"
    echo "$legacy_hits" | head -3 | sed 's/^/  /'
    errors=$((errors + 1))
  fi

  # PUBLIC FIELD CHECK (skip properties, static, const, readonly, event)
  local public_fields
  public_fields=$(echo "$content" | grep -nE '^\s*public\s+(int|float|double|string|bool|Vector[234]|Quaternion|Transform|GameObject|Rigidbody|Collider|Renderer|Color|Sprite|Texture|AudioClip|AnimationCurve|LayerMask)\s+' | grep -vE '(static|const|readonly|event|\{.*get|=>|\()' || true)
  if [ -n "$public_fields" ]; then
    echo "FAIL [public-field] ${file}: prefer [SerializeField] private"
    echo "$public_fields" | head -3 | sed 's/^/  /'
    errors=$((errors + 1))
  fi

  # ONE CLASS PER FILE (sort -u handles partial classes)
  local type_count
  type_count=$(echo "$content" | grep -oE '(class|struct|enum|interface)\s+\w+' | awk '{print $2}' | sort -u | wc -l | tr -d ' ')
  if [ "$type_count" -gt 1 ]; then
    echo "FAIL [one-type-per-file] ${file}: ${type_count} distinct types (max 1)"
    errors=$((errors + 1))
  fi

  # TOP-DOWN ARCHITECTURE: cross-system internal refs
  local file_ns
  file_ns=$(echo "$content" | grep -oE 'namespace R8EOX\.(\w+)' | head -1 | sed 's/namespace R8EOX\.//' || true)
  if [ -n "$file_ns" ]; then
    local cross_ref
    cross_ref=$(echo "$content" | grep -nE "using R8EOX\.\w+\.Internal" | grep -v "R8EOX\.${file_ns}\.Internal" || true)
    if [ -n "$cross_ref" ]; then
      echo "FAIL [top-down] ${file}: cross-system internal reference"
      echo "$cross_ref" | head -3 | sed 's/^/  /'
      errors=$((errors + 1))
    fi
  fi

  # BANNED: SendMessage / BroadcastMessage
  local send_msg
  send_msg=$(echo "$content" | grep -nE '\.(SendMessage|BroadcastMessage)\s*\(' | grep -vE '^\s*[0-9]*:\s*//' || true)
  if [ -n "$send_msg" ]; then
    echo "FAIL [banned-pattern] ${file}: SendMessage/BroadcastMessage banned"
    echo "$send_msg" | head -1 | sed 's/^/  /'
    errors=$((errors + 1))
  fi

  # BANNED: FindObjectOfType (exempt: editor builder scripts that scan scenes by design)
  case "$file" in
    Assets/Scripts/Editor/*) : ;;  # Editor builders legitimately scan active scenes
    *)
      local find_obj
      find_obj=$(echo "$content" | grep -nE 'FindObjectOfType|FindObjectsOfType|FindAnyObjectByType|FindFirstObjectByType' | grep -vE '^\s*[0-9]*:\s*//' || true)
      if [ -n "$find_obj" ]; then
        echo "FAIL [banned-pattern] ${file}: FindObjectOfType banned — pass references through parent"
        echo "$find_obj" | head -1 | sed 's/^/  /'
        errors=$((errors + 1))
      fi
      ;;
  esac

  # BANNED: Singleton .Instance
  local singleton
  singleton=$(echo "$content" | grep -nE '\.Instance\b' | grep -vE '^\s*[0-9]*:\s*//' || true)
  if [ -n "$singleton" ]; then
    echo "FAIL [singleton] ${file}: .Instance access banned — use dependency injection"
    echo "$singleton" | head -1 | sed 's/^/  /'
    errors=$((errors + 1))
  fi

  return $errors
}
